[package]
name = "noisy-wallpaper"
version = "0.1.0"
edition = "2024"

[dependencies]
noise = "0.9.0"
pollster = "0.4.0"
smithay-client-toolkit = {version = "0.20.0"}
wayland-backend = {version = "0.3.0", features = ["client_system"]}
wayland-client = "0.31.12"
wgpu = "27.0.1"
